#!/usr/bin/env bash
# creates a symbolic link (-s option) between the Nginx configuration file and the enabled sites directory 
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
