#!/usr/bin/env bash
# This script displays "4-bad luck from China", "9-bad luck from Japan" and "17-bad luck from Italy" for the 4th, 9th and 17th iterations respectively.

count=1
while [ $count -le 20 ]; do
    case $count in
        4)
            echo "$count and then bad luck from China"
            ;;
        9)
            echo "$count and then bad luck from Japan"
            ;;
        17)
            echo "$count and then bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
    count=$((count + 1))
done
