#!/usr/bin/env bash
# Configure Nginx to be running as the nginx user

# Change Nginx user to nginx
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Change listening port to 8080
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

# Check if Nginx is running as nginx user and listening on port 8080
pgrep -a nginx
sudo netstat -tulpn | grep :8080
