#!/usr/bin/env bash
# Generates an RSA key pair with 4096 bits
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N "betty"

echo "RSA key pair created successfully!"
echo "Private key saved as ~/.ssh/school"
echo "Public key saved as ~/.ssh/school.pub"
